version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      VERSION: "${VERSION:-latest}"
      TYPE: "${TYPE:-PAPER}"
      FORCE_REDOWNLOAD: "${FORCE_REDOWNLOAD:-FALSE}"
      MEMORY: ${MEMORY:-1}
      EXEC_DIRECTLY: "${EXEC_DIRECTLY:-true}"
      STOP_SERVER_ANNOUNCE_DELAY: "${STOP_SERVER_ANNOUNCE_DELAY:-5}"
      TZ: "Asia/Tehran:${TZ}"
      GUI: "${GUI:-false}"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./minecraft-data:/data