version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      VERSION: "latest:${VERSION}"
      TYPE: "PAPER:${TYPE}"
      FORCE_REDOWNLOAD: "FALSE:${FORCE_REDOWNLOAD}"
      MEMORY: 1:${MEMORY}
      EXEC_DIRECTLY: "true:${EXEC_DIRECTLY}"
      STOP_SERVER_ANNOUNCE_DELAY: "5:${STOP_SERVER_ANNOUNCE_DELAY}"
      TZ: "Asia/Tehran:${TZ}"
      GUI: "false:${GUI}"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./minecraft-data:/data